# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'skillup8' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for skillup8
  pod 'RealmSwift'

  target 'skillup8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'skillup8UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
