# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-FlickrAPI-sk11' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-FlickrAPI-sk11
  pod 'Alamofire', '4.5.1'
  pod 'ObjectMapper', '3.0.0'
  pod ‘AlamofireImage’

  target 'ios-FlickrAPI-sk11Tests' do
    inherit! :search_paths
    # Pods for testing
  pod 'ObjectMapper', '3.0.0'
  end

end
